### ISSUE TITLE
RubyGem yanked

### ISSUE THREAD

**Issue by GSI** [feedreader/jekyll-planet#4]
Why did you yank the gem from RubyGems?

It worked flawlessly, but now every project depending on it has to be updated, causing additional maintenance/cost.

**Comment by geraldb** [comment]
Sorry to hear that you depend on the old jekyll-planet gem. I didn't expect any user because I never heard anything from anyone, really. More serious:  It's really just a single-file script and was an example, that is, you have to change the code yourself (e.g. what keys you include in your front matter, how many items you include with your query, etc.) anyway - isn't it easier to just copy the single-file script and change it?

**Comment by GSI** [comment]
Yep, it's probably easier. In our case our daily CI suddenly started to fail due to the missing gem. We updated the corresponding files.

It's always good to have old versions available - especially in Jekyll where even vulnerabilities in gems usually don't affect the resulting site's security.

Thanks for a useful tool and the good explanations in your readme. Silence doesn't mean the absense of people appreciating your work :)
